##===- projects/sample/tools/Makefile ----------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#

DIRS=b1
#DIRS=p0 p0cpp p1 p1cpp p2 p2cpp p3 p3cpp p4

#p7cpp

include $(LEVEL)/Makefile.common
