##===- projects/sample/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#

DIRS=summary SummaryCpp dominance cfg Transform GCM
#DIRS=sample summary SummaryCpp dominance cfg LICM CSE Transform SLP GCM
# LC3 GCM rt FT

include $(LEVEL)/Makefile.common
